sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: dddd

  redis:
    host: localhost
    port: 6379
    password: dddd

  wechat:
    appid: wx07f45fa36ea4684e
    secret: 9ba3928f02c6a6054468ed2ea7813fcd
